version: "3"

services:

  main:
    image: ${DOCKER_HUB_USER:-vfarcic}/go-demo-2:${TAG:-latest}
    environment:
      - DB=db
    networks:
      - proxy
      - default
    healthcheck:
      disable: true
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=${SERVICE_PATH:-/demo}
        - com.df.reqPathSearch=${SERVICE_PATH:-/demo}
        - com.df.reqPathReplace=/demo
        - com.df.port=8080

  db:
    image: mongo
    networks:
      - default

networks:
  default:
    external: false
  proxy:
    external: true
